import React from 'react';

// Comprehensive D1 basketball team logos with ESPN CDN URLs
const TEAM_LOGOS = {
  // Abbreviated forms (for display)
  'usf': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/58.png',
  'ucf': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2116.png',
  'usc': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/30.png',
  'unc': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/153.png',
  'vcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2670.png',
  'lsu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/99.png',
  'smu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2567.png',
  'tcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2628.png',
  'byu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/252.png',
  'fgcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/526.png',
  'fau': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2226.png',
  'fiu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2229.png',
  'utsa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2636.png',
  'utep': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2638.png',
  'umass': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/113.png',
  'umbc': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2378.png',
  'uncw': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/350.png',
  'uncg': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2430.png',
  'pitt': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/221.png',
  'uconn': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/41.png',
  'ucla': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/26.png',
  'unlv': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2439.png',
  'uab': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/5.png',
  
  // Power conferences
  'alabama': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/333.png',
  'arizona': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/12.png',
  'arizona state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/9.png',
  'arkansas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/8.png',
  'auburn': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2.png',
  'baylor': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/239.png',
  'boston college': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/103.png',
  'byu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/252.png',
  'butler': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2086.png',
  'california': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/25.png',
  'cincinnati': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2132.png',
  'clemson': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/228.png',
  'colorado': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/38.png',
  'uconn': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/41.png',
  'creighton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/156.png',
  'dayton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2168.png',
  'depaul': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/305.png',
  'duke': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/150.png',
  'florida': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/57.png',
  'florida state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/52.png',
  'georgetown': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/46.png',
  'georgia': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/61.png',
  'georgia tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/59.png',
  'gonzaga': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2250.png',
  'houston': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/248.png',
  'illinois': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/356.png',
  'indiana': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/84.png',
  'iowa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2294.png',
  'iowa state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/66.png',
  'kansas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2305.png',
  'kansas state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2306.png',
  'kentucky': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/96.png',
  'louisville': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/97.png',
  'lsu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/99.png',
  'marquette': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/269.png',
  'maryland': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/120.png',
  'memphis': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/235.png',
  'miami': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2390.png',
  'michigan': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/130.png',
  'michigan state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/127.png',
  'minnesota': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/135.png',
  'mississippi state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/344.png',
  'missouri': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/142.png',
  'nc state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/152.png',
  'nebraska': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/158.png',
  'north carolina': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/153.png',
  'northwestern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/77.png',
  'notre dame': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/87.png',
  'ohio state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/194.png',
  'oklahoma': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/201.png',
  'oklahoma state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/197.png',
  'ole miss': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/145.png',
  'oregon': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2483.png',
  'oregon state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/204.png',
  'penn state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/213.png',
  'pittsburgh': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/221.png',
  'providence': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2507.png',
  'purdue': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2509.png',
  'rutgers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/164.png',
  'seton hall': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2550.png',
  'smu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2567.png',
  'south carolina': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2579.png',
  "st. john's": 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2599.png',
  'stanford': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/24.png',
  'syracuse': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/183.png',
  'tcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2628.png',
  'tennessee': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2633.png',
  'texas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/251.png',
  'texas a&m': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/245.png',
  'texas tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2641.png',
  'ucf': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2116.png',
  'ucla': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/26.png',
  'usc': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/30.png',
  'utah': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/254.png',
  'vanderbilt': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/238.png',
  'villanova': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/222.png',
  'virginia': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/258.png',
  'virginia tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/259.png',
  'wake forest': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/154.png',
  'washington': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/264.png',
  'washington state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/265.png',
  'west virginia': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/277.png',
  'wisconsin': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/275.png',
  'xavier': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2752.png',
  
  // Mid-majors and other D1
  'south florida': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/58.png',
  'usf': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/58.png',
  'buffalo': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2084.png',
  'vcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2670.png',
  "saint mary's": 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2608.png',
  "saint joseph's": 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2603.png',
  'saint louis': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/139.png',
  'st. bonaventure': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/179.png',
  'san diego state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/21.png',
  'san francisco': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2539.png',
  'loyola chicago': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2350.png',
  'loyola marymount': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2351.png',
  'loyola maryland': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2352.png',
  'george mason': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2244.png',
  'george washington': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/45.png',
  'davidson': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2166.png',
  'richmond': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/257.png',
  'rhode island': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/227.png',
  'temple': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/218.png',
  'tulsa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/202.png',
  'tulane': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2655.png',
  'wichita state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2724.png',
  'nevada': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2440.png',
  'unlv': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2439.png',
  'new mexico': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/167.png',
  'boise state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/68.png',
  'colorado state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/36.png',
  'utah state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/328.png',
  'fresno state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/278.png',
  'air force': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2005.png',
  'wyoming': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2751.png',
  'santa clara': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2541.png',
  'pepperdine': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2492.png',
  'san diego': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/301.png',
  'pacific': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/279.png',
  'portland': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2501.png',
  
  // MAC
  'akron': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2006.png',
  'ball state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2050.png',
  'bowling green': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/189.png',
  'central michigan': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2117.png',
  'eastern michigan': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2199.png',
  'kent state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2309.png',
  'miami (oh)': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/193.png',
  'northern illinois': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2459.png',
  'ohio': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/195.png',
  'toledo': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2649.png',
  'western michigan': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2711.png',
  
  // American Athletic
  'charlotte': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2429.png',
  'east carolina': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/151.png',
  'fau': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2226.png',
  'florida atlantic': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2226.png',
  'fiu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2229.png',
  'florida international': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2229.png',
  'navy': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2426.png',
  'north texas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/249.png',
  'rice': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/242.png',
  'uab': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/5.png',
  'utsa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2636.png',
  
  // Missouri Valley
  'belmont': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2057.png',
  'bradley': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/71.png',
  'drake': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2181.png',
  'evansville': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/339.png',
  'illinois state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2287.png',
  'indiana state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/282.png',
  'missouri state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2623.png',
  'murray state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/93.png',
  'northern iowa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2460.png',
  'southern illinois': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/79.png',
  'valparaiso': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2674.png',
  
  // Ivy League
  'brown': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/225.png',
  'columbia': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/171.png',
  'cornell': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/172.png',
  'dartmouth': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/159.png',
  'harvard': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/108.png',
  'penn': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/219.png',
  'princeton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/163.png',
  'yale': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/43.png',
  
  // SWAC/MEAC/HBCUs
  'alabama a&m': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2010.png',
  'alabama state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2011.png',
  'alcorn state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2016.png',
  'arkansas-pine bluff': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2029.png',
  'bethune-cookman': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2065.png',
  'coppin state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2154.png',
  'delaware state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2169.png',
  'florida a&m': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/50.png',
  'grambling state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2755.png',
  'hampton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2261.png',
  'howard': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/47.png',
  'jackson state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2296.png',
  'mississippi valley state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2400.png',
  'morgan state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2419.png',
  'norfolk state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2450.png',
  'prairie view a&m': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2504.png',
  'south carolina state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2569.png',
  'southern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2582.png',
  'texas southern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2640.png',
  
  // All D1 schools - comprehensive list
  'abilene christian': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2000.png',
  'arkansas state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2032.png',
  'arkansas-little rock': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2031.png',
  'bellarmine': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/91.png',
  'bryant': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2803.png',
  'chicago state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2130.png',
  'detroit mercy': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2174.png',
  'detroit': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2174.png',
  'gardner-webb': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2241.png',
  'green bay': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2739.png',
  'houston christian': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2277.png',
  'houston baptist': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2277.png',
  'iupui': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/85.png',
  'maryland eastern shore': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2379.png',
  'umes': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2379.png',
  'miami (fl)': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2390.png',
  'milwaukee': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/270.png',
  'wisconsin-milwaukee': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/270.png',
  'uw-milwaukee': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/270.png',
  'saint francis (pa)': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2598.png',
  'st. francis (pa)': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2598.png',
  // Note: UMass Lowell removed - was using wrong logo ID (Louisiana-Monroe's)
  'vmi': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2678.png',
  'virginia military': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2678.png',
  'albany': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/399.png',
  'american': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/44.png',
  'appalachian state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2026.png',
  'army': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/349.png',
  'austin peay': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2046.png',
  'binghamton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2066.png',
  'boston university': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/104.png',
  'bucknell': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2083.png',
  'campbell': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2097.png',
  'charleston': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/232.png',
  'cleveland state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2146.png',
  'coastal carolina': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/324.png',
  'colgate': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2142.png',
  'delaware': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/48.png',
  'denver': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2172.png',
  'drexel': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2182.png',
  'duquesne': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2184.png',
  'eastern kentucky': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2198.png',
  'eastern washington': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/331.png',
  'fgcu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/526.png',
  'florida gulf coast': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/526.png',
  'fordham': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2230.png',
  'furman': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/231.png',
  'georgia southern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/290.png',
  'georgia state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2247.png',
  'grand canyon': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2253.png',
  'hawaii': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/62.png',
  'hofstra': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2275.png',
  'holy cross': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/107.png',
  'idaho': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/70.png',
  'iona': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/314.png',
  'james madison': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/256.png',
  'la salle': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2325.png',
  'lafayette': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/322.png',
  'lehigh': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2329.png',
  'liberty': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2335.png',
  'lipscomb': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/288.png',
  'long island university': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/112358.png',
  'long beach state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/299.png',
  'louisiana': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/309.png',
  'louisiana tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2348.png',
  'maine': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/311.png',
  'manhattan': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2363.png',
  'marist': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2368.png',
  'marshall': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/276.png',
  'middle tennessee': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2393.png',
  'millikin': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2396.png',
  'monmouth': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2405.png',
  'montana': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/149.png',
  'montana state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/147.png',
  'morehead state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2413.png',
  'new mexico state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/166.png',
  'niagara': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/315.png',
  'north dakota': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/155.png',
  'north dakota state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2449.png',
  'northeastern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/111.png',
  'northern arizona': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2464.png',
  'northern colorado': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2458.png',
  'northwestern state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2466.png',
  'oakland': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2473.png',
  'old dominion': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/295.png',
  'oral roberts': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/198.png',
  'portland state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2502.png',
  'quinnipiac': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2514.png',
  'radford': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2515.png',
  'rider': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2520.png',
  'robert morris': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2523.png',
  'sacramento state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/16.png',
  'samford': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2535.png',
  'sam houston': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2534.png',
  'san jose state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/23.png',
  'siena': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2561.png',
  'south alabama': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/6.png',
  'south dakota': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/233.png',
  'south dakota state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2571.png',
  'southeast missouri': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2546.png',
  'southern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2582.png',
  'southern miss': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2572.png',
  'southern utah': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/253.png',
  'stetson': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/56.png',
  'stony brook': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2619.png',
  'texas state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/326.png',
  'towson': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/119.png',
  'troy': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2653.png',
  'umass': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/113.png',
  'umbc': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2378.png',
  'unc greensboro': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2430.png',
  'unc wilmington': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/350.png',
  'uncw': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/350.png',
  'utep': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2638.png',
  'vermont': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/261.png',
  'wagner': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2681.png',
  'weber state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2692.png',
  'western carolina': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2717.png',
  'western kentucky': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/98.png',
  'west georgia': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2698.png',
  'mercyhurst': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2902.png',
  'new haven': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2497.png',
  // savannah state removed - was using Sam Houston's logo ID
  'nebraska-omaha': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2437.png',
  'south carolina upstate': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2908.png',
  'illinois-chicago': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/82.png',
  'citadel': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2643.png',
  'kansas city': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/140.png',
  'southeast missouri state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2546.png',
  'grambling': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2755.png',
  'st. francis brooklyn': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2597.png',
  // winston-salem state removed - was using Wichita State's logo ID
  'centenary': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2123.png',
  'william & mary': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2729.png',
  'wofford': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2747.png',
  'wright state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2750.png',
  'youngstown state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2754.png',
  
  // Additional D1 schools
  'cal poly': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/13.png',
  'cal state bakersfield': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2934.png',
  'cal state fullerton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2239.png',
  'cal state northridge': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2463.png',
  'csun': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2463.png',
  'california baptist': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/366090.png',
  'canisius': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2099.png',
  'central arkansas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2110.png',
  'central connecticut': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2115.png',
  'central connecticut state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2115.png',
  'charleston southern': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2127.png',
  'chattanooga': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/236.png',
  'east tennessee state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2193.png',
  'etsu': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2193.png',
  'eastern illinois': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2197.png',
  'elon': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2210.png',
  'fairfield': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2217.png',
  'fairleigh dickinson': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2218.png',
  // Note: Florida Southern is D2 - no ESPN logo available
  'hartford': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/42.png',
  'high point': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2272.png',
  'idaho state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/304.png',
  'incarnate word': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2916.png',
  'jacksonville': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/294.png',
  'jacksonville state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/55.png',
  'kennesaw state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/338.png',
  'lamar': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2320.png',
  'le moyne': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2333.png',
  'lindenwood': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2815.png',
  'little rock': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2031.png',
  'longwood': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2344.png',
  'louisiana-monroe': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2349.png',
  'mcneese': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2377.png',
  'mcneese state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2377.png',
  'mercer': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2382.png',
  'merrimack': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2771.png',
  "mount st. mary's": 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2389.png',
  'nc central': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2428.png',
  'north carolina central': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2428.png',
  'new hampshire': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/160.png',
  'new orleans': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2443.png',
  'nicholls': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2447.png',
  'nicholls state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2447.png',
  'njit': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2885.png',
  'north alabama': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2453.png',
  'north carolina a&t': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2448.png',
  'north florida': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2454.png',
  'northern kentucky': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/94.png',
  'omaha': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2437.png',
  'presbyterian': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2506.png',
  'purdue fort wayne': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2870.png',
  'queens': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/3101.png',
  'sacred heart': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2529.png',
  "saint peter's": 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2612.png',
  'san jose state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/23.png',
  'san jose state university': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/23.png',
  'seattle': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2547.png',
  'siu edwardsville': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2565.png',
  'siue': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2565.png',
  'southeastern louisiana': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2545.png',
  'southern indiana': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2568.png',
  'st. thomas': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2900.png',
  'stephen f. austin': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2617.png',
  'sfa': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2617.png',
  'stonehill': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2618.png',
  'tarleton': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/178.png',
  'tarleton state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/178.png',
  'tennessee state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2634.png',
  'tennessee tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2635.png',
  // texas a&m-commerce removed - was using TCU's logo ID
  'texas a&m-corpus christi': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/357.png',
  'utrgv': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/292.png',
  'texas rio grande valley': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/292.png',
  'uc davis': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/302.png',
  'uc irvine': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/300.png',
  'uc riverside': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/27.png',
  'uc san diego': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/28.png',
  'uc santa barbara': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2540.png',
  'unc asheville': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2427.png',
  'ut arlington': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/250.png',
  'uta': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/250.png',
  'ut martin': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2630.png',
  'utah tech': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/3101.png',
  'dixie state': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/3101.png',
  'utah valley': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/3084.png',
  'western illinois': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2710.png',
  'winthrop': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/ncaa/500/2745.png',

  // NBA Teams
  'boston celtics': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/2.png',
  'brooklyn nets': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/17.png',
  'new york knicks': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/18.png',
  'philadelphia 76ers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/20.png',
  'toronto raptors': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/28.png',
  'chicago bulls': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/4.png',
  'cleveland cavaliers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/5.png',
  'detroit pistons': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/8.png',
  'indiana pacers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/11.png',
  'milwaukee bucks': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/15.png',
  'atlanta hawks': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/1.png',
  'charlotte hornets': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/30.png',
  'miami heat': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/14.png',
  'orlando magic': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/19.png',
  'washington wizards': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/27.png',
  'denver nuggets': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/7.png',
  'minnesota timberwolves': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/16.png',
  'oklahoma city thunder': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/25.png',
  'portland trail blazers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/22.png',
  'utah jazz': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/26.png',
  'golden state warriors': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/9.png',
  'los angeles clippers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/12.png',
  'los angeles lakers': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/13.png',
  'phoenix suns': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/21.png',
  'sacramento kings': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/23.png',
  'dallas mavericks': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/6.png',
  'houston rockets': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/10.png',
  'memphis grizzlies': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/29.png',
  'new orleans pelicans': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/3.png',
  'san antonio spurs': 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/24.png',
};

// Aliases map - maps various spellings to canonical lowercase names that have logos
const SCHOOL_ALIASES = {
  // Abbreviated forms
  'usf': 'south florida',
  'usf bulls': 'south florida',
  'university of south florida': 'south florida',
  'ucf': 'ucf',
  'uconn': 'uconn',
  'unc': 'north carolina',
  'vcu': 'vcu',
  'lsu': 'lsu',
  'smu': 'smu',
  'tcu': 'tcu',
  'byu': 'byu',
  'fgcu': 'fgcu',
  'fau': 'florida atlantic',
  'fiu': 'fiu',
  'utsa': 'utsa',
  'utep': 'utep',
  'umass': 'umass',
  'umbc': 'umbc',
  'uncw': 'uncw',
  'uncg': 'unc greensboro',
  'ulm': 'louisiana-monroe',
  'pitt': 'pittsburgh',
  
  // Full name variations
  'connecticut': 'uconn',
  'university of connecticut': 'uconn',
  // Connecticut College and other CT schools now handled by LOGO_BLOCKLIST
  // Other Connecticut state schools
  'eastern connecticut': 'eastern connecticut state',
  'eastern connecticut state': 'eastern connecticut state',
  'southern connecticut': 'southern connecticut state',
  'southern connecticut state': 'southern connecticut state',
  'western connecticut': 'western connecticut state',
  'western connecticut state': 'western connecticut state',
  'north carolina state': 'nc state',
  'n.c. state': 'nc state',
  "saint john's": "st. john's",
  "st john's": "st. john's",
  "st. mary's": "saint mary's",
  "st. mary's college": "saint mary's",
  "st. joseph's": "saint joseph's",
  "st. louis": "saint louis",
  "st. louis university": "saint louis",
  
  // Accented name variations
  'san josé state': 'san jose state',
  'san josé state university': 'san jose state',
  'são paulo': 'sao paulo',
  'méxico': 'mexico',
  
  // En-dash to hyphen variants
  'bethune–cookman': 'bethune-cookman',
  'arkansas–little rock': 'arkansas-little rock',
  'arkansas–pine bluff': 'arkansas-pine bluff',
  'gardner–webb': 'gardner-webb',
  // winston-salem state removed - was using wrong logo
  'wisconsin–green bay': 'green bay',
  'wisconsin–milwaukee': 'milwaukee',
  'louisiana–monroe': 'louisiana-monroe',
  'louisiana–lafayette': 'louisiana',
  // texas a&m-commerce removed - was using wrong logo
  'texas a&m–corpus christi': 'texas a&m-corpus christi',
  
  // Army/Navy variations
  'army west point': 'army',
  'army black knights': 'army',
  
  // California variations
  'cal': 'california',
  'california': 'california',
  'cal berkeley': 'california',
  'uc berkeley': 'california',
  
  // Little Rock variations
  'ualr': 'little rock',
  
  // Green Bay variations
  'wisconsin-green bay': 'green bay',
  'uwgb': 'green bay',
  
  'university of alabama': 'alabama',
  'university of kentucky': 'kentucky',
  'university of north carolina': 'north carolina',
  'university of kansas': 'kansas',
  'university of michigan': 'michigan',
  'university of florida': 'florida',
  'university of texas': 'texas',
  'michigan state university': 'michigan state',
  'ohio state university': 'ohio state',
  'the ohio state university': 'ohio state',
  'penn state university': 'penn state',
  'pennsylvania state university': 'penn state',
  'florida state university': 'florida state',
  'iowa state university': 'iowa state',
  'kansas state university': 'kansas state',
  'oklahoma state university': 'oklahoma state',
  'arizona state university': 'arizona state',
  'oregon state university': 'oregon state',
  'washington state university': 'washington state',
  'colorado state university': 'colorado state',
  'utah state university': 'utah state',
  'brigham young university': 'byu',
  'brigham young': 'byu',
  'southern methodist university': 'smu',
  'texas christian university': 'tcu',
  'university of central florida': 'ucf',
  'university of southern california': 'usc',
  'southern california': 'usc',
  'university of california, los angeles': 'ucla',
  'louisiana state university': 'lsu',
  'louisiana state': 'lsu',
  'virginia polytechnic': 'virginia tech',
  'georgia institute of technology': 'georgia tech',
  'university of pittsburgh': 'pittsburgh',
  'university of miami': 'miami',
  'miami university': 'miami (oh)',
  'university of notre dame': 'notre dame',
  'university of mississippi': 'ole miss',
  'mississippi': 'ole miss',
  'virginia commonwealth university': 'vcu',
  'virginia commonwealth': 'vcu',
  'university at buffalo': 'buffalo',
  'suny buffalo': 'buffalo',
  'gonzaga university': 'gonzaga',
  'villanova university': 'villanova',
  'georgetown university': 'georgetown',
  'duke university': 'duke',
  'stanford university': 'stanford',
  'northwestern university': 'northwestern',
  'vanderbilt university': 'vanderbilt',
  'wake forest university': 'wake forest',
  'syracuse university': 'syracuse',
  'clemson university': 'clemson',
  'auburn university': 'auburn',
  'baylor university': 'baylor',
  'purdue university': 'purdue',
  'creighton university': 'creighton',
  'marquette university': 'marquette',
  'xavier university': 'xavier',
  'butler university': 'butler',
  'seton hall university': 'seton hall',
  'providence college': 'providence',
  'depaul university': 'depaul',
  'university of memphis': 'memphis',
  'university of houston': 'houston',
  'university of cincinnati': 'cincinnati',
  'west virginia university': 'west virginia',
  'university of louisville': 'louisville',
  'university of san francisco': 'san francisco',
  'loyola marymount university': 'loyola marymount',
  'lmu': 'loyola marymount',
  'loyola university chicago': 'loyola chicago',
  'loyola-chicago': 'loyola chicago',
  'loyola (illinois)': 'loyola chicago',
  'loyola illinois': 'loyola chicago',
  'loyola': 'loyola chicago',  // Default Loyola to Chicago (biggest program)
  'loyola maryland': 'loyola maryland',
  'loyola university maryland': 'loyola maryland',
  'loyola (md)': 'loyola maryland',
  'loyola md': 'loyola maryland',
  'university of dayton': 'dayton',
  'san diego state university': 'san diego state',
  'sdsu': 'san diego state',
  'boise state university': 'boise state',
  'fresno state university': 'fresno state',
  'wisconsin-whitewater': 'wisconsin-whitewater',
  'uw-whitewater': 'wisconsin-whitewater',
  
  // College/University suffix variations
  'merrimack college': 'merrimack',
  'california baptist university': 'california baptist',
  'cal baptist': 'california baptist',
  'cbu': 'california baptist',
  "st. peter's": "saint peter's",
  "st peter's": "saint peter's",
  "st peter's college": "saint peter's",
  "saint peter's university": "saint peter's",
  "st peter's": "st. peter's",
  "st peter's college": "st. peter's",
  "saint joseph's university": "saint joseph's",
  "st. joseph's university": "saint joseph's",
  "saint mary's college": "saint mary's",
  'sacred heart university': 'sacred heart',
  'monmouth university': 'monmouth',
  'wagner college': 'wagner',
  'wofford college': 'wofford',
  'davidson college': 'davidson',
  'colgate university': 'colgate',
  'cornell university': 'cornell',
  'drake university': 'drake',
  'duquesne university': 'duquesne',
  'furman university': 'furman',
  'samford university': 'samford',
  'princeton university': 'princeton',
  'bucknell university': 'bucknell',
  'marshall university': 'marshall',
  'valparaiso university': 'valparaiso',
  'towson university': 'towson',
  'lindenwood university': 'lindenwood',
  
  // State university variations
  'alabama a&m university': 'alabama a&m',
  'alcorn state university': 'alcorn state',
  'appalachian state university': 'appalachian state',
  'bethune-cookman university': 'bethune-cookman',
  'central michigan university': 'central michigan',
  'eastern kentucky university': 'eastern kentucky',
  'eastern michigan university': 'eastern michigan',
  'eastern washington university': 'eastern washington',
  'florida international university': 'fiu',
  'grambling state university': 'grambling',
  'howard university': 'howard',
  'jackson state university': 'jackson state',
  'jacksonville state university': 'jacksonville state',
  'kent state university': 'kent state',
  'mississippi state university': 'mississippi state',
  'new mexico state university': 'new mexico state',
  'nicholls state university': 'nicholls state',
  'nicholls': 'nicholls state',
  'north carolina central university': 'north carolina central',
  'northern arizona university': 'northern arizona',
  'portland state university': 'portland state',
  'prairie view a&m university': 'prairie view a&m',
  'sam houston state university': 'sam houston',
  'sam houston state': 'sam houston',
  'south carolina state university': 'south carolina state',
  'southeastern louisiana university': 'southeastern louisiana',
  'western carolina university': 'western carolina',
  
  // University of X variations
  'university at albany': 'albany',
  'university of central arkansas': 'central arkansas',
  'university of iowa': 'iowa',
  'university of louisiana at monroe': 'louisiana-monroe',
  'university of maine': 'maine',
  'university of oklahoma': 'oklahoma',
  'university of oregon': 'oregon',
  'university of pennsylvania': 'penn',
  'pennsylvania': 'penn',
  'university of richmond': 'richmond',
  'university of tennessee at martin': 'ut martin',
  'university of utah': 'utah',
  'university of the incarnate word': 'incarnate word',
  
  // Other common variations
  'ut rio grande valley': 'utrgv',
  'uic': 'illinois-chicago',
  'umkc': 'kansas city',
  'liu': 'long island university',
  'long island': 'long island university',
  'usc upstate': 'south carolina upstate',
  "st. john's university": "st. john's",
  'the citadel': 'citadel',
  "hawai'i": 'hawaii',
  'hawaii': 'hawaii',
  "mount st. mary's": "mount st. mary's",
  // east texas a&m removed - was aliased to wrong school
  'houston christian university': 'houston christian',
  'houston baptist/houston christian': 'houston christian',
  'houston baptist': 'houston christian',
  'ipfw/fort wayne/purdue fort wayne': 'purdue fort wayne',
  'ipfw': 'purdue fort wayne',
  'fort wayne': 'purdue fort wayne',
  'iu indy': 'iupui',
  'saint francis': 'st. francis (pa)',
  'west georgia': 'west georgia',
  'university of west georgia': 'west georgia',
  'tennessee st': 'tennessee state',
  'the university of texas': 'texas',
  
  // Torvik "St." abbreviations -> full "State" names
  'alabama st.': 'alabama state',
  'alcorn st.': 'alcorn state',
  'appalachian st.': 'appalachian state',
  'arizona st.': 'arizona state',
  'arkansas st.': 'arkansas state',
  'ball st.': 'ball state',
  'boise st.': 'boise state',
  'chicago st.': 'chicago state',
  'cleveland st.': 'cleveland state',
  'colorado st.': 'colorado state',
  'coppin st.': 'coppin state',
  'delaware st.': 'delaware state',
  'florida st.': 'florida state',
  'fresno st.': 'fresno state',
  'georgia st.': 'georgia state',
  'grambling st.': 'grambling',
  'idaho st.': 'idaho state',
  'illinois st.': 'illinois state',
  'indiana st.': 'indiana state',
  'iowa st.': 'iowa state',
  'jackson st.': 'jackson state',
  'jacksonville st.': 'jacksonville state',
  'kansas st.': 'kansas state',
  'kennesaw st.': 'kennesaw state',
  'kent st.': 'kent state',
  'mcneese st.': 'mcneese state',
  'michigan st.': 'michigan state',
  'mississippi st.': 'mississippi state',
  'missouri st.': 'missouri state',
  'montana st.': 'montana state',
  'morehead st.': 'morehead state',
  'morgan st.': 'morgan state',
  'murray st.': 'murray state',
  'nicholls st.': 'nicholls state',
  'norfolk st.': 'norfolk state',
  'north dakota st.': 'north dakota state',
  'northwestern st.': 'northwestern state',
  'ohio st.': 'ohio state',
  'oklahoma st.': 'oklahoma state',
  'oregon st.': 'oregon state',
  'penn st.': 'penn state',
  'portland st.': 'portland state',
  'sacramento st.': 'sacramento state',
  'sam houston st.': 'sam houston',
  'san diego st.': 'san diego state',
  'san jose st.': 'san jose state',
  'south carolina st.': 'south carolina state',
  'south dakota st.': 'south dakota state',
  'tarleton st.': 'tarleton state',
  'tennessee st.': 'tennessee state',
  'texas st.': 'texas state',
  'utah st.': 'utah state',
  'washington st.': 'washington state',
  'weber st.': 'weber state',
  'wichita st.': 'wichita state',
  'wright st.': 'wright state',
  'youngstown st.': 'youngstown state',
  
  // Torvik special names
  'arkansas pine bluff': 'arkansas-pine bluff',
  'bethune cookman': 'bethune-cookman',
  'cal st. bakersfield': 'cal state bakersfield',
  'cal st. fullerton': 'cal state fullerton',
  'cal st. northridge': 'cal state northridge',
  'east tennessee st.': 'east tennessee state',
  'etsu': 'east tennessee state',
  'gardner webb': 'gardner-webb',
  'illinois chicago': 'illinois-chicago',
  'long beach st.': 'long beach state',
  'louisiana monroe': 'louisiana-monroe',
  'massachusetts': 'umass',
  'miami fl': 'miami',
  'miami oh': 'miami (oh)',
  'mississippi valley st.': 'mississippi valley state',
  'nebraska omaha': 'nebraska-omaha',
  'new mexico st.': 'new mexico state',
  'southeast missouri st.': 'southeast missouri state',
  'st. francis ny': 'st. francis brooklyn',
  'tennessee martin': 'ut martin',
  'texas a&m corpus chris': 'texas a&m-corpus christi',
  'the citadel': 'citadel',
  'umkc': 'kansas city',
  'usc upstate': 'south carolina upstate',
  // winston salem st. and savannah st. aliases removed - underlying entries had wrong logos
  
  // Additional variations
  'mercyhurst': 'mercyhurst',
  'new haven': 'new haven',
  'loyola md': 'loyola maryland',
  'unc greensboro': 'unc greensboro',
  'uncg': 'unc greensboro',
  'little rock': 'arkansas-little rock',
  'tennessee tech': 'tennessee tech',
  'bucknell': 'bucknell',
  'coastal carolina': 'coastal carolina',
  'chattanooga': 'chattanooga',
  'texas a&m': 'texas a&m',
  'oral roberts': 'oral roberts',
  'cal baptist': 'california baptist',
  'southern utah': 'southern utah',
  "saint mary's": "saint mary's",
  'san francisco': 'san francisco',
  'valparaiso': 'valparaiso',
  'wyoming': 'wyoming',
  'ohio': 'ohio',
  'fairleigh dickinson': 'fairleigh dickinson',
  'stonehill': 'stonehill',
  'north dakota': 'north dakota',
  'lamar': 'lamar',
  'incarnate word': 'incarnate word',
};

const _cache = new Map();

// Schools that should NOT get a D1 logo (they're different schools with similar names)
const LOGO_BLOCKLIST = new Set([
  // D3/D2/NAIA/JuCo schools that share names with D1 schools
  'connecticut college',        // D3 NESCAC, NOT UConn
  'georgetown college',         // D2 in Kentucky, NOT Georgetown (Big East)
  'rhode island college',       // D3, NOT URI (A-10)
  'southern illinois college',  // Community college, NOT SIU
  'notre dame college',         // D2 in Ohio, NOT Notre Dame
  'washington college',         // D3 in Maryland, NOT UW
  'colorado college',           // D3, NOT Colorado
  'howard college',             // JuCo in Texas, NOT Howard University
  'temple college',             // JuCo in Texas, NOT Temple
  'jacksonville college',       // JuCo, NOT Jacksonville University
  'columbia college',           // Various D2/D3 schools, NOT Columbia (Ivy)
  'texas college',              // NAIA, NOT Texas
  
  // Schools with wrong logo assignments in ESPN - block to prevent wrong logos
  'savannah state',             // Has own logo, not Sam Houston
  'savannah state university',
  'winston-salem state',        // Has own logo, not Wichita State
  'winston-salem state university',
  'winston salem state',
  'winston salem state university',
  'texas a&m-commerce',         // Has own logo, not TCU
  'texas a&m–commerce',
  'texas a&m commerce',
  'east texas a&m',             // Same as Texas A&M-Commerce
  'umass lowell',               // Has own logo, not Louisiana-Monroe
  'mass lowell',
  'queens',                     // Queens University of Charlotte, different from Utah Tech
  'queens university',
  
  // Other Connecticut schools (not UConn)
  'central connecticut',
  'central connecticut state', 
  'central connecticut state university',
  'ccsu',
  'eastern connecticut',
  'eastern connecticut state',
  'southern connecticut',
  'southern connecticut state',
  'western connecticut',
  'western connecticut state',
]);

export const getTeamLogoUrl = (teamName) => {
  if (!teamName) return null;
  
  let key = teamName.toLowerCase().trim();
  if (_cache.has(key)) return _cache.get(key);
  
  // Check blocklist first - these schools should NOT get a logo
  if (LOGO_BLOCKLIST.has(key)) {
    _cache.set(key, null);
    return null;
  }
  
  // Try direct lookup
  let url = TEAM_LOGOS[key];
  
  // Try alias
  if (!url && SCHOOL_ALIASES[key]) {
    url = TEAM_LOGOS[SCHOOL_ALIASES[key]];
  }
  
  // Try stripping common suffixes
  if (!url) {
    const stripped = key
      .replace(/\s+university$/i, '')
      .replace(/^university\s+of\s+/i, '')
      .replace(/\s+college$/i, '')
      .replace(/\s+st\.?$/i, ' state')
      .trim();
    
    // Check blocklist for stripped version too
    if (LOGO_BLOCKLIST.has(stripped)) {
      _cache.set(key, null);
      return null;
    }
    
    url = TEAM_LOGOS[stripped];
    if (!url && SCHOOL_ALIASES[stripped]) {
      url = TEAM_LOGOS[SCHOOL_ALIASES[stripped]];
    }
  }
  
  _cache.set(key, url || null);
  return url || null;
};

export const TeamLogo = ({ team, size = 20, style = {} }) => {
  const url = getTeamLogoUrl(team);
  if (!url) return null;
  
  return (
    <img
      src={url}
      alt=""
      style={{
        width: `${size}px`,
        height: `${size}px`,
        objectFit: 'contain',
        verticalAlign: 'middle',
        flexShrink: 0,
        ...style
      }}
      loading="lazy"
      onError={(e) => { e.target.style.display = 'none'; }}
    />
  );
};

export const TeamWithLogo = ({ team, size = 18, style = {}, nameStyle = {}, gap = '0.4rem' }) => {
  if (!team) return null;
  const url = getTeamLogoUrl(team);
  
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap, ...style }}>
      {url && (
        <img
          src={url}
          alt=""
          style={{ width: `${size}px`, height: `${size}px`, objectFit: 'contain', flexShrink: 0 }}
          loading="lazy"
          onError={(e) => { e.target.style.display = 'none'; }}
        />
      )}
      <span style={nameStyle}>{team}</span>
    </span>
  );
};

export default TEAM_LOGOS;
